[project]
name = "open-data-product-berlin-building-industry-monthly-source-aligned"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
]
